#!/usr/bin/env python

import argparse
import sys

parser = argparse.ArgumentParser()
group = parser.add_mutually_exclusive_group()
group.add_argument("-n", "--node", help="Run this instance as a node",
					action="store_true")
group.add_argument("-c", "--controller", help="Run this instance as a controller",
					action="store_true")
parser.add_argument("-p", "--api_port", help="Specify port API will bind to",
					type=int, default=8080)
parser.add_argument("-a", "--api_address", help="Specify address API will bind to",
					type=str, default='0.0.0.0')
parser.add_argument("-P", "--gui_port", help="Specify port GUI will bind to",
					type=int, default=80)
parser.add_argument("-A", "--gui_address", help="Specify address GUI will bind to",
					type=str, default='0.0.0.0')

args = parser.parse_args()

if not args.node and not args.controller:
	print 'Specify if this instance is a controller or node'
	sys.exit(1)