#!/usr/bin/env python 

import argparse
import sys
import yaml

from watchtower import config
from watchtower.node import manager

parser = argparse.ArgumentParser()
group = parser.add_mutually_exclusive_group()
group.add_argument("-n", "--node", help="Run this instance as a node",
					action="store_true")
group.add_argument("-c", "--controller", help="Run this instance as a controller",
					action="store_true")
parser.add_argument("--config", help="Config file")

args = parser.parse_args()

if not args.node and not args.controller:
	print 'Specify if this instance is a controller or node'
	sys.exit(1)

if not args.config:
	print 'Provide a yaml formatted config file'
	sys.exit(1)
else:
	with open(args.config, 'r') as f:
		_config = yaml.load(f)
		for key in _config:
			setattr(config, key, _config[key])


if args.node:
	_manager = manager.Manager()